# Generated by Django 4.2.4 on 2023-12-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_moods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to test in the App', max_length=50)),
                ('Moods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.moods')),
            ],
        ),
    ]
