# Generated by Django 4.2.4 on 2023-12-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Moods',
            new_name='moods',
        ),
    ]
