# Generated by Django 4.2.4 on 2024-02-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_moods_test_moods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_meditation', models.FileField(blank=True, null=True, upload_to='mp3s/')),
                ('guided_meditation', models.FileField(blank=True, null=True, upload_to='mp3s/')),
                ('read_relaxation', models.FileField(upload_to='pdfs/')),
                ('film_relaxation', models.FileField(blank=True, null=True, upload_to='mp4s/')),
                ('moods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.moods')),
            ],
        ),
    ]
