# Generated by Django 4.2.4 on 2024-02-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='moods',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
