# Generated by Django 4.2.4 on 2024-03-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_files_film_relaxation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moods',
            name='category_moods',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Category_type_Test',
        ),
    ]
