# Generated by Django 4.2.4 on 2024-05-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_moods_category_moods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moods',
            name='explanation',
            field=models.CharField(help_text='description from the User text your mood in the App', max_length=50),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=300)),
                ('order', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='login.test')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=300)),
                ('question_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.questions')),
            ],
        ),
    ]
