# Generated by Django 4.2.4 on 2024-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_moods_category_moods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moods',
            name='explanation',
            field=models.CharField(help_text='description from the User text your mood in the App', max_length=50),
        ),
    ]
