# Generated by Django 4.2.4 on 2024-05-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_moods_explanation_questions_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.option')),
                ('quetion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
        ),
    ]
