# Generated by Django 4.2.4 on 2024-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='moods',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='imagen/'),
        ),
    ]
