# Generated by Django 4.2.4 on 2024-06-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_moods_imagens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='moods',
            new_name='mood',
        ),
    ]
