# Generated by Django 4.2.4 on 2024-07-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_option_option_option_description_option_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
