# Generated by Django 4.2.4 on 2024-08-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_option_description_alter_option_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='question_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='login.questions'),
        ),
    ]
