# Generated by Django 4.2.4 on 2024-08-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_option_options_option_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='description',
        ),
    ]
