# Generated by Django 4.2.4 on 2024-10-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_option_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quetion',
            new_name='question',
        ),
    ]
