# Generated by Django 4.2.4 on 2024-11-05 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0017_rename_quetion_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moods',
            name='explanation',
            field=models.CharField(help_text='Description of the mood in the App', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email from the User in the App', max_length=100)),
                ('password', models.CharField(help_text='Password to enter in the App', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.profile'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
