# Generated by Django 4.2.4 on 2025-01-29 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0018_alter_moods_explanation_profile_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RenameField(
            model_name='files',
            old_name='type',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='question_key',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='files',
            name='location',
        ),
        migrations.RemoveField(
            model_name='moods',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files/'),
        ),
        migrations.AddField(
            model_name='moods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/moods/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moods',
            name='explanation',
            field=models.CharField(help_text='Description of the mood in the app', max_length=50),
        ),
        migrations.AlterField(
            model_name='moods',
            name='name',
            field=models.CharField(help_text='Name of the mood in the app', max_length=20),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(help_text='Name of the option', max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of the option in the question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(help_text='Type of the option (e.g., multiple choice)', max_length=20),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(help_text='Value of the option (e.g., "True/False")', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='order',
            field=models.IntegerField(help_text='Order of the question in the test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(help_text='Name of the test in the app', max_length=50),
        ),
    ]
