# Generated by Django 4.2.4 on 2025-02-05 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0019_alter_profile_options_rename_type_files_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Cliente'), ('admin', 'Administrador')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/files,/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_type',
            field=models.CharField(choices=[('mp3', 'MP3'), ('mp4', 'MP4'), ('pdf', 'PDF')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
