# Generated by Django 4.2.4 on 2025-04-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_remove_profile_date_of_birth_remove_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Cliente'), ('admin', 'Administrador')], default='client', max_length=20),
        ),
    ]
